import dynamic from "next/dynamic";
const DndProviderComponent = dynamic(
  () => import("../dnd-provider.component"),
  {
    ssr: false,
  },
);

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function CategoriesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <DndProviderComponent>{children}</DndProviderComponent>;
}
